# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yK65ov53enPq_R6JHeJ8fzaaUmS-2NXw
"""

import pandas as pd

# Sample dataset
data = pd.DataFrame([
    ['Good', 'High', 'Many', 'Good', 'Yes'],
    ['Good', 'Medium', 'Many', 'Average', 'Yes'],
    ['Average', 'High', 'Few', 'Good', 'Yes'],
    ['Poor', 'Medium', 'Many', 'Poor', 'No'],
    ['Good', 'Low', 'Few', 'Average', 'No'],
    ['Average', 'Medium', 'Few', 'Average', 'No']
], columns=['Programming', 'Academics', 'Projects', 'Communication', 'Label'])

data

def find_s(data):
    positive = data[data['Label'] == 'Yes'].drop('Label', axis=1)
    hypothesis = positive.iloc[0].values.tolist()

    for index, row in positive.iterrows():
        for i in range(len(hypothesis)):
            if hypothesis[i] != row[i]:
                hypothesis[i] = '?'
    return hypothesis

most_specific_hypothesis = find_s(data)
print("Most Specific Hypothesis (Find-S):", most_specific_hypothesis)

def candidate_elimination(data):
    attributes = data.columns[:-1]
    S = ['0'] * len(attributes)
    G = [['?'] * len(attributes)]

    for index, row in data.iterrows():
        x = row[:-1].values
        y = row[-1]

        if y == 'Yes':
            for i in range(len(S)):
                if S[i] == '0':
                    S[i] = x[i]
                elif S[i] != x[i]:
                    S[i] = '?'
            G = [g for g in G if all(g[i] == '?' or g[i] == x[i] for i in range(len(g)))]

        else:
            new_G = []
            for g in G:
                for i in range(len(g)):
                    if g[i] == '?':
                        for val in data[attributes[i]].unique():
                            if val != x[i]:
                                new_hypothesis = g.copy()
                                new_hypothesis[i] = val
                                new_G.append(new_hypothesis)
                    elif g[i] == x[i]:
                        break
            if new_G:
                G = new_G

    return S, G

S_boundary, G_boundary = candidate_elimination(data)
print("Specific boundary (S):", S_boundary)
print("General boundary (G):", G_boundary)